### ISSUE TITLE
Feedrate: ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#140]
See https://community.octoprint.org/t/layer-and-height-not-displayed/18508/6
```
2020-04-18 08:22:09,507 - octoprint.plugin - ERROR - Error while calling plugin DisplayLayerProgress
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/__init__.py", line 1151, in on_event
    self._updateDisplay(UPDATE_DISPLAY_REASON_FRONTEND_CALL)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/__init__.py", line 644, in _updateDisplay
    self._updateDisplayWorkerMethod(updateReason)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/__init__.py", line 674, in _updateDisplayWorkerMethod
    feedrate = self._calculateFeedrate(self._feedrate)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/__init__.py", line 874, in _calculateFeedrate
    newFeedrate = float(feedrateFactor) * float(feedrate)
ValueError: could not convert string to float: 
```

**Comment by OllisGit** [comment]
Fixed
