### ISSUE TITLE
Handle GCode-Scripts e.g. travel_speed

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-DisplayLayerProgress#87]
In OctoPrint it is possible to use gcode-scripts: https://docs.octoprint.org/en/master/features/gcode_scripts.html?highlight=snippet

Check if the plugin could handle this scripts, maybe pickup the right gcode-command from payload.

Capture from Forum (https://community.octoprint.org/t/wip-new-print-history-plugin/1633/16):

```
2019-08-18 01:04:30,985 - octoprint.util.comm - ERROR - Error while processing hook DisplayLayerProgress for phase sending and command G1 Z+0.5 E-5 X-20 Y-20 F{travel_speed}:
Traceback (most recent call last):
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3220, in _process_command_phase
hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/init.py", line 249, in sendingGCodeHook
self._updateDisplay(UPDATE_DISPLAY_REASON_FEEDRATE_CHANGED)
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/init.py", line 442, in _updateDisplay
feedrate = self._calculateFeedrate(self._feedrate)
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress/init.py", line 560, in _calculateFeedrate
newFeedrate = float(feedrateFactor) * float(feedrate)
ValueError: could not convert string to float:
```

**Comment by OllisGit** [comment]
not worth to analyse...no user user report such an issue -> closed
